site_name: safeboot
site_description: >-
  Debian package to enable UEFI SecureBoot, enroll your own hardware
  backed platform key, sign the kernel and initrd, decrypt the disk with
  the TPM, and enable system integrity protection with dmverity
repo_url: https://github.com/osresearch/safeboot/
site_url: https://safeboot.dev/
edit_uri: ""
theme:
  name: material
  custom_dir: docs/custom/
  logo: images/logo.png
  favicon: images/favicon.ico
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
    heading: IBM Plex Sans
extra_css: [extra.css]
markdown_extensions:
  - toc
  - admonition
  - md_in_html
  - extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - mermaid2
nav:
  - Overview: 'index.md'
  - Installation: 'install.md'
  - Frequently Asked Questions: 'faq.md'
  - Threat Model: 'threats.md'
  - Remote Attestation: 'attestation.md'
  - Chain of Trust: 'chain-of-trust.md'
  - safeboot subcommands: 'safeboot.md'
  - tpm2-attest subcommands: 'tpm2-attest.md'
